{{- if and .Values.api.enabled .Values.api.highAvailability.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "pixshar.fullname" . }}-api
  labels:
    {{- include "pixshar.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.api.highAvailability.minAvailable }}
  selector:
    matchLabels:
      {{- include "pixshar.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: api
{{- end }}
