apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pixshar.configMapName" . }}
  labels:
    {{- include "pixshar.labels" . | nindent 4 }}
data:
  NODE_ENV: "production"
  API_PORT: {{ .Values.api.port | quote }}
  API_URL: {{ .Values.config.apiUrl | quote }}
  WEB_URL: {{ .Values.config.webUrl | quote }}
  BETTER_AUTH_URL: {{ .Values.config.betterAuthUrl | quote }}
  DATABASE_URL: "file:./prisma/prod.db"
  S3_ENDPOINT: {{ .Values.config.s3Endpoint | quote }}
  S3_BUCKET: {{ .Values.config.s3Bucket | quote }}
  S3_REGION: {{ .Values.config.s3Region | quote }}
  {{- if .Values.config.s3PublicUrl }}
  S3_PUBLIC_URL: {{ .Values.config.s3PublicUrl | quote }}
  {{- end }}
  {{- if .Values.config.s3PublicEndpoint }}
  S3_PUBLIC_ENDPOINT: {{ .Values.config.s3PublicEndpoint | quote }}
  {{- end }}
  DOWNLOAD_DEBOUNCE_SECONDS: {{ .Values.config.downloadDebounceSeconds | quote }}
