{{- if .Values.serviceMonitor.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "pixshar.api.fullname" . }}
  labels:
    {{- include "pixshar.labels" . | nindent 4 }}
    release: {{ .Values.serviceMonitor.prometheusRelease }}
spec:
  selector:
    matchLabels:
      {{- include "pixshar.api.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: api
      path: /metrics
      interval: {{ .Values.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
{{- if .Values.imageProcessor.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "pixshar.imageProcessor.fullname" . }}
  labels:
    {{- include "pixshar.labels" . | nindent 4 }}
    release: {{ .Values.serviceMonitor.prometheusRelease }}
spec:
  selector:
    matchLabels:
      {{- include "pixshar.imageProcessor.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: metrics
      path: /metrics
      interval: {{ .Values.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
{{- end }}
{{- end }}
