{{- if .Values.web.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "pixshar.web.fullname" . }}
  labels:
    {{- include "pixshar.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.web.port }}
      targetPort: web
      protocol: TCP
      name: web
  selector:
    {{- include "pixshar.web.selectorLabels" . | nindent 4 }}
{{- end }}
